# Generated by Django 3.2.18 on 2023-02-25 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.FloatField(default=1, max_length=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
