# Generated by Django 3.2.18 on 2023-02-27 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_auto_20230226_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='alc',
        ),
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.FloatField(default=1, max_length=10, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='product',
            name='measurement_unit',
            field=models.CharField(default='г', max_length=200, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.FloatField(default=1, max_length=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена'),
        ),
    ]
