# Generated by Django 3.2.18 on 2023-02-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measurement_unit',
            field=models.CharField(blank=True, default='л', max_length=200, null=True, verbose_name='Единица измерения'),
        ),
    ]
