# Generated by Django 3.2.18 on 2023-02-27 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_alter_product_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.FloatField(default=50, max_length=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='measurement_unit',
            field=models.CharField(blank=True, default='мл', max_length=200, null=True, verbose_name='Единица измерения'),
        ),
    ]
