# Generated by Django 3.2.18 on 2023-02-27 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_auto_20230227_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.FloatField(default=50, max_length=10, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.FloatField(default=250, max_length=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена'),
        ),
    ]
