# Generated by Django 3.2.18 on 2023-02-27 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0008_auto_20230227_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.FloatField(blank=True, default=50, max_length=10, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Количество'),
        ),
    ]
