# Generated by Django 3.2.18 on 2023-02-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0010_product_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='menu_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер меню'),
        ),
    ]
