# Generated by Django 3.2.18 on 2023-02-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0011_product_menu_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='menu_number',
            field=models.PositiveIntegerField(default=2, verbose_name='Номер меню'),
        ),
    ]
