# Generated by Django 3.2.18 on 2023-02-27 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0012_alter_product_menu_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.FloatField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='measurement_unit',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Единица измерения'),
        ),
    ]
