# Generated by Django 3.2.18 on 2023-02-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0013_auto_20230227_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_wait',
            field=models.BooleanField(default=False),
        ),
    ]
