# Generated by Django 3.2.18 on 2023-02-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0014_user_is_wait'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.PositiveIntegerField(blank=True, max_length=4, null=True),
        ),
    ]
