# Generated by Django 3.2.18 on 2023-03-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0015_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
