MENU = 'MENU'
OFFER = 'OFFER'
PRODUCT_IN_CART = 'PRODUCT_IN_CART'
PRODUCT_OFFER = 'PRODUCT_OFFER'
BACK_TO_MENU = 'BACK_TO_MENU'
CHECKHOUT = 'CHECKHOUT'
WAIT = 'WAIT'
READY = 'READY'
CANCEL = 'CANCEL'
DELETE = 'DELETE'

BUTTON_BACK_IN_PLACE = 'IN_PLACE_BACK'

SECRET_LEVEL_BUTTON = 'SCRT_LVL'
CONFIRM_DECLINE_BROADCAST = 'CNFM_DCLN_BRDCST'
CONFIRM_BROADCAST = 'CONFIRM'
DECLINE_BROADCAST = 'DECLINE'

MENU_IMG_1 = 'AgACAgIAAxkBAAICZGP7rBjDEjrKWPia0NU-6QuwCvOCAALIxDEbuxbZSwQj9KOQJwXjAQADAgADeQADLgQ'
MENU_IMG_2 = 'AgACAgIAAxkBAAICZmP7rB_H3aHbqwVmZtrzXCPo-C9GAALKxDEbuxbZS3XHbOUwEt9aAQADAgADeQADLgQ'

AFISHA = [
    'AgACAgIAAxkBAAICuGP7xCjBgGkijcN0G6dRJcPLMSovAALwxTEbuxbhS2XNujNCEtaOAQADAgADeQADLgQ',
    'AgACAgIAAxkBAAICumP7xDSr61Y3AAHr4wwnIx3lSpcIXwAC8cUxG7sW4UuD0m8C0IvutgEAAwIAA3kAAy4E',
    'AgACAgIAAxkBAAICu2P7xDRwXRby4tsPk_2nIZk8MUZnAALyxTEbuxbhSzcHBC3rOi8QAQADAgADeQADLgQ',
    'AgACAgIAAxkBAAICvGP7xDTcMBz3ExxZtj4OwgE_EMkyAALzxTEbuxbhS-4RTi8ZvKXSAQADAgADeQADLgQ',
    'AgACAgIAAxkBAAICvWP7xDTb70a_Hg-ZuW-vBsJAtQW3AAL0xTEbuxbhSxrqhrEzbuC7AQADAgADeQADLgQ',
    'AgACAgIAAxkBAAICvmP7xDS4NldagTfyiBdPaYiy8yhEAAL1xTEbuxbhS8Gj5ENGfqPFAQADAgADeQADLgQ',
    'AgACAgIAAxkBAAICv2P7xDRyzG5zrToo1LKf7izTvNaoAAL2xTEbuxbhS_GkUkidCkmrAQADAgADeQADLgQ'
]

PASSWORD_ADMIN = '123123'
PASSWORD_MODER = '123'
