MENU = 'MENU'
OFFER = 'OFFER'
PRODUCT_IN_CART = 'PRODUCT_IN_CART'
PRODUCT_OFFER = 'PRODUCT_OFFER'
BACK_TO_MENU = 'BACK_TO_MENU'
CHECKHOUT = 'CHECKHOUT'
WAIT = 'WAIT'
READY = 'READY'
CANCEL = 'CANCEL'
DELETE = 'DELETE'

BUTTON_BACK_IN_PLACE = 'IN_PLACE_BACK'

SECRET_LEVEL_BUTTON = 'SCRT_LVL'
CONFIRM_DECLINE_BROADCAST = 'CNFM_DCLN_BRDCST'
CONFIRM_BROADCAST = 'CONFIRM'
DECLINE_BROADCAST = 'DECLINE'

MENU_IMG_1 = 'AgACAgIAAxkBAAMmY_45kwH3zuhEC_ljPC5dCvAFyHQAAknEMRuh_PBLPRkIFXs5qgwBAAMCAAN5AAMuBA'
MENU_IMG_2 = 'AgACAgIAAxkBAAMnY_45k-xeQpZXHvjhOwgBvwKwHFIAAkrEMRuh_PBLULCtqhBNaZABAAMCAAN5AAMuBA'

AFISHA = [
    'AgACAgIAAxkBAAMYY_45ipka_iXnhYTqHAiUlw0dlGwAAvDFMRu7FuFLw4QpcjUyN6cBAAMCAAN5AAMuBA',
    'AgACAgIAAxkBAAMZY_45itXLK60l11WRoCn4xq2V6XsAAvHFMRu7FuFLUyb28SDjgYoBAAMCAAN5AAMuBA',
    'AgACAgIAAxkBAAMaY_45im3Lf0YL84HkFqjrrw8Xgn0AAvLFMRu7FuFL6GOyGM4hijUBAAMCAAN5AAMuBA',
    'AgACAgIAAxkBAAMbY_45imcEsSshSEpskkPsCLVNnKwAAvPFMRu7FuFL5k8XPZ1TMBsBAAMCAAN5AAMuBA',
    'AgACAgIAAxkBAAMcY_45igWekbgr1qRnO2Mw0pobywMAAvTFMRu7FuFLAAHbTpxqRpY3AQADAgADeQADLgQ',
    'AgACAgIAAxkBAAMdY_45iqsc-bLaw6vSWLM1KqOytqYAAvXFMRu7FuFLK1DR42kr-tQBAAMCAAN5AAMuBA',
    'AgACAgIAAxkBAAMeY_45ipx_H2qVTezllCZVYbI2hJEAAvbFMRu7FuFLdBOkS2UMj4UBAAMCAAN5AAMuBA'
]

PASSWORD_ADMIN = '123123'
PASSWORD_MODER = '123'
